name: safety_tracker_app
description: A tracking application that offers safety to users in form of groups.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  location: ^3.1.0
  google_maps_flutter: ^1.0.6
  flutter_polyline_points: ^0.2.4
  geolocator: ^5.3.1
  flutter_google_places: ^0.2.6
  firebase_storage: ^5.2.0
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  provider: ^4.3.2+3
  flutter_swiper: ^1.1.6
  camera: ^0.5.8+17
  path: ^1.7.0
  path_provider: ^1.6.24
  image_picker: ^0.6.7+14
  carousel_slider: ^2.3.1
  font_awesome_flutter: ^8.10.1
  shared_preferences: ^0.5.12+4
  cloud_firestore: ^0.14.1+3
  splashscreen: 1.2.0
  flutter_signin_button: ^1.0.0
  intl: ^0.16.1
  google_sign_in: ^4.5.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen/Oxygen-Regular.ttf
        - asset: fonts/Oxygen/Oxygen-Bold.ttf
        - asset: fonts/Oxygen/Oxygen-Light.ttf
          style: normal
    - family: Work Sans
      fonts:
        - asset: fonts/Work Sans/static/WorkSans-Bold.ttf
        - asset: fonts/Work Sans/static/WorkSans-Italic.ttf
        - asset: fonts/Work Sans/static/WorkSans-Light.ttf
        - asset: fonts/Work Sans/static/WorkSans-Regular.ttf
          weight: 600


